services:
  dnsmasq-leases-ui:
    container_name: dnsmasq-leases-ui
    build: .
    restart: unless-stopped
    environment:
      HOME: /tmp
      XDG_RUNTIME_DIR: /tmp
      PORT: "3008"
    network_mode: host
    volumes:
      - /var/lib/dnsmasq:/var/lib/dnsmasq:ro
