name: Ruff Format

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format dnsmasq_leases_ui.py

      - name: Commit formatted file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No formatting changes."
          else
            git add dnsmasq_leases_ui.py
            git commit -m "Format dnsmasq_leases_ui.py with Ruff"
            git push
          fi
